### PR TITLE
Refactor to use Aphrodite for stylesheets, take 2

### PR DESCRIPTION
**Pull request by j-hannah**
@sirkitree I created a new branch to sort through it. It wasn't actually in the merge conflict resolution, but a bug. I guess I missed it because you had to restart the server to see it. I think it's sorted out.

### CODE REVIEW

**Comment by sirkitree** [comment]
Still getting this error using this branch. I've tried on windows and mac now so I don't think it's my setup. Steps to reproduce:

1. cd into js-report
1. npm install
1. npm run server
1. go to localhost:3000 in browser

* notice that nothing loads in browser
* notice in terminal the following error message 
```
(node:78) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot automatically buffer without a document
```

**Comment by sirkitree** [comment]
According to [this](http://stackoverflow.com/questions/39716569/nodejs-unhandledpromiserejectionwarning#39718611) it may be something in the tests. Trying to track it down.

**Comment by sirkitree** [comment]
I found a way to capture the `unhandledRejection` to get some more details. See [SO](http://stackoverflow.com/questions/31472439/catch-all-unhandled-javascript-promise-rejections#32940253).

I added to `src/index.js`:
```
...
import process from 'process';
...
process.on('unhandledRejection', function(err, promise) {
    console.error('Unhandled rejection (promise: ', promise, ', reason: ', err, ').');
});
```

This gives me the following detail in the terminal now:
```
Unhandled rejection (promise:  Promise {                                                                                                                                                                         
  <rejected> Error: Cannot automatically buffer without a document                                                                                                                                               
    at injectGeneratedCSSOnce (/mnt/c/Users/sirki/repos/js-report/node_modules/aphrodite/lib/inject.js:145:23)                                                                                                   
    at injectStyleOnce (/mnt/c/Users/sirki/repos/js-report/node_modules/aphrodite/lib/inject.js:169:9)                                                                                                           
    at injectAndGetClassName (/mnt/c/Users/sirki/repos/js-report/node_modules/aphrodite/lib/inject.js:250:5)                                                                                                     
    at css (/mnt/c/Users/sirki/repos/js-report/node_modules/aphrodite/lib/exports.js:146:54)                                                                                                                     
    at App (/mnt/c/Users/sirki/repos/js-report/src/components/App/App.js:11:28)                                                                                                                                  
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (/mnt/c/Users/sirki/repos/js-report/node_modules/react/lib/ReactCompositeComponent.js:308:14)                                              
    at ReactCompositeComponentWrapper._constructComponent (/mnt/c/Users/sirki/repos/js-report/node_modules/react/lib/ReactCompositeComponent.js:284:19)                                                          
    at ReactCompositeComponentWrapper.mountComponent (/mnt/c/Users/sirki/repos/js-report/node_modules/react/lib/ReactCompositeComponent.js:187:21)                                                               
    at Object.mountComponent (/mnt/c/Users/sirki/repos/js-report/node_modules/react/lib/ReactReconciler.js:47:35)                                                                                                
    at ReactCompositeComponentWrapper.performInitialMount (/mnt/c/Users/sirki/repos/js-report/node_modules/react/lib/ReactCompositeComponent.js:370:34) } , reason:  Error: Cannot automatically buffer without a
document                                                                                                                                                                                                         
    at injectGeneratedCSSOnce (/mnt/c/Users/sirki/repos/js-report/node_modules/aphrodite/lib/inject.js:145:23)                                                                                                   
    at injectStyleOnce (/mnt/c/Users/sirki/repos/js-report/node_modules/aphrodite/lib/inject.js:169:9)                                                                                                           
    at injectAndGetClassName (/mnt/c/Users/sirki/repos/js-report/node_modules/aphrodite/lib/inject.js:250:5)                                                                                                     
    at css (/mnt/c/Users/sirki/repos/js-report/node_modules/aphrodite/lib/exports.js:146:54)                                                                                                                     
    at App (/mnt/c/Users/sirki/repos/js-report/src/components/App/App.js:11:28)                                                                                                                                  
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (/mnt/c/Users/sirki/repos/js-report/node_modules/react/lib/ReactCompositeComponent.js:308:14)                                              
    at ReactCompositeComponentWrapper._constructComponent (/mnt/c/Users/sirki/repos/js-report/node_modules/react/lib/ReactCompositeComponent.js:284:19)                                                          
    at ReactCompositeComponentWrapper.mountComponent (/mnt/c/Users/sirki/repos/js-report/node_modules/react/lib/ReactCompositeComponent.js:187:21)                                                               
    at Object.mountComponent (/mnt/c/Users/sirki/repos/js-report/node_modules/react/lib/ReactReconciler.js:47:35)                                                                                                
    at ReactCompositeComponentWrapper.performInitialMount (/mnt/c/Users/sirki/repos/js-report/node_modules/react/lib/ReactCompositeComponent.js:370:34) ).                                                       
```

The following line stands out:
`at App (/mnt/c/Users/sirki/repos/js-report/src/components/App/App.js:11:28) `

This is our call to `css()` which is imported from `aphrodite/no-important`

So I can't tell if we're using it wrong, or if this is an error with aphrodite...

**Comment by j-hannah** [comment]
@sirkitree May have to do with server side rendering.

**Comment by j-hannah** [comment]
I will take a look later tonight after I get done with the day job. That is if you don't fix it first. 😄

**Comment by sirkitree** [comment]
Another clue is that I received the same error after losing internet, but this time slightly different:
```
 node:2716) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: getaddrinfo ENOTFOUND cdn.contentful.com cdn.contentful.com:443
```

This has be thinking that we need to handle the promised data coming back from contentful - so probably where we're using axios.

**Comment by sirkitree** [comment]
Of course, nothing here touched axios...

**Comment by j-hannah** [comment]
@sirkitree OK, I think I have it fixed now. It was because of the server rendering. I missed it because I didn't test the server rendering. 😳 I thought - hey, I'm not implementing Aphrodite server side. It turns out that if you're doing server side rendering, you need to handle Aphrodite server side as well. At least that's what I ran into. Can you test to confirm I have it sorted out?

**Comment by sirkitree** [comment]
Works! Thanks :)

**Pull request merged**
